name: pusher_client
description: |
  A Pusher Channels client plugin for Flutter targeting Android and iOS. It 
  wraps pusher-websocket-java v2.2.5 and pusher-websocket-swift v8.0.0.
version: 1.0.2
homepage: https://github.com/chinloyal/pusher_client
documentation: https://github.com/chinloyal/pusher_client/blob/master/README.md


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^1.10.4
  json_serializable: ^3.5.0
  json_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.github.chinloyal.pusher_client
        pluginClass: PusherClientPlugin
      ios:
        pluginClass: PusherClientPlugin
